#!/bin/bash

if [ ! -f "/var/lib/webosbrew/init.d/homescreen_cleaner" ]; then
	curl -s -L https://raw.githubusercontent.com/LyonaDeSad/homescreen_cleaner/main/homescreen_cleaner > /var/lib/webosbrew/init.d/homescreen_cleaner
	chmod +x /var/lib/webosbrew/init.d/homescreen_cleaner
	/var/lib/webosbrew/init.d/homescreen_cleaner && exit 0
fi
mkdir -p /tmp/homescreen_cleaner
pkill -f com.webos.app.home
